apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
  labels:
    app: filebrowser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebrowser
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      nodeSelector:
        kubernetes.io/hostname: amd11
      containers:
        - name: filebrowser
          image: docker.io/filebrowser/filebrowser:latest
          imagePullPolicy: IfNotPresent
          args:
            - "--config"
            - "/config/.filebrowser.json"
          volumeMounts:
            - name: filebrowser-config
              mountPath: /config
            - name: music-storage
              mountPath: /srv/Music
          resources:
            requests:
              cpu: 20m
              memory: 40Mi
            limits:
              memory: 150Mi

        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
          imagePullPolicy: IfNotPresent
          args:
            - "--config=/etc/oauth2-proxy/oauth2-proxy.cfg"
          ports:
            - containerPort: 4180
              hostPort: 4180
              name: proxy-http
          volumeMounts:
            - name: oauth2-config
              mountPath: /etc/oauth2-proxy
          resources:
            requests:
              cpu: 20m
              memory: 40Mi
            limits:
              memory: 120Mi

      volumes:
        - name: filebrowser-config
          hostPath:
            path: /opt/filebrowser/config
            type: Directory
        - name: music-storage
          hostPath:
            path: /opt/navidrome/music
            type: Directory
        - name: oauth2-config
          hostPath:
            path: /opt/oauth2-proxy
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: filebrowser
spec:
  selector:
    app: filebrowser
  ports:
    - protocol: TCP
      port: 4180
      targetPort: 4180
