apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  labels:
    app: otel-collector
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      prometheus:
        config:
          scrape_configs:
            - job_name: 'uptime-kuma'
              scrape_interval: 30s
              static_configs:
                - targets: ['uptime-kuma:3001']
              basic_auth:
                username: 'scraper'
                password: 'uk1_otel2026'

    processors:
      batch:
        timeout: 5s
        send_batch_size: 256

    exporters:
      prometheus:
        endpoint: 0.0.0.0:8889
      debug:
        verbosity: basic

    service:
      pipelines:
        metrics:
          receivers: [otlp, prometheus]
          processors: [batch]
          exporters: [prometheus, debug]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  labels:
    app: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      nodeSelector:
        kubernetes.io/hostname: arm10
      containers:
        - name: otel-collector
          image: docker.io/otel/opentelemetry-collector-contrib:0.119.0
          imagePullPolicy: IfNotPresent
          args: ["--config=/etc/otelcol-contrib/config.yaml"]
          ports:
            - containerPort: 4317
              name: otlp-grpc
            - containerPort: 4318
              name: otlp-http
            - containerPort: 8889
              name: prom-export
            - containerPort: 8888
              name: self-metrics
          volumeMounts:
            - name: config-vol
              mountPath: /etc/otelcol-contrib
          resources:
            requests:
              cpu: 20m
              memory: 32Mi
            limits:
              memory: 128Mi
      volumes:
        - name: config-vol
          configMap:
            name: otel-collector-config
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
spec:
  selector:
    app: otel-collector
  ports:
    - name: otlp-grpc
      protocol: TCP
      port: 4317
      targetPort: 4317
    - name: otlp-http
      protocol: TCP
      port: 4318
      targetPort: 4318
    - name: prom-export
      protocol: TCP
      port: 8889
      targetPort: 8889
    - name: self-metrics
      protocol: TCP
      port: 8888
      targetPort: 8888
