apiVersion: apps/v1
kind: Deployment
metadata:
  name: umami
  labels:
    app: umami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: umami
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: umami
    spec:
      nodeSelector:
        kubernetes.io/hostname: arm10
      containers:
        - name: umami
          image: ghcr.io/umami-software/umami:postgresql-v2.13.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: DATABASE_TYPE
              value: "postgresql"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: UMAMI_DATABASE_URL
            - name: APP_SECRET
              value: "super_secret_app_key_umami_2026_tokyo"
          resources:
            requests:
              cpu: 30m
              memory: 128Mi
            limits:
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: umami
spec:
  type: NodePort
  selector:
    app: umami
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30003
