apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-kuma
  labels:
    app: uptime-kuma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptime-kuma
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: uptime-kuma
    spec:
      nodeSelector:
        kubernetes.io/hostname: arm10
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - "1.1.1.1"
          - "8.8.8.8"
      containers:
        - name: uptime-kuma
          image: docker.io/louislam/uptime-kuma:1.23.17
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
              name: http
          volumeMounts:
            - name: uptime-data
              mountPath: /app/data
          resources:
            requests:
              cpu: 20m
              memory: 64Mi
            limits:
              memory: 256Mi
      volumes:
        - name: uptime-data
          hostPath:
            path: /opt/uptime-kuma
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma
spec:
  type: NodePort
  selector:
    app: uptime-kuma
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30002
