apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alert-rules
  namespace: observability
  labels:
    app: grafana
data:
  rules.yaml: |
    apiVersion: 1
    groups:
      - orgId: 1
        name: Kubernetes Health
        folder: Kubernetes Alerts
        interval: 1m
        rules:
          - uid: pod_crashloop
            title: PodCrashLoopBackOff
            condition: C
            data:
              - refId: A
                relativeTimeRange:
                  from: 300
                  to: 0
                datasourceUid: VictoriaMetrics
                model:
                  editorMode: code
                  expr: rate(kube_pod_container_status_restarts_total[5m]) > 0
                  intervalMs: 1000
                  maxDataPoints: 43200
                  refId: A
              - refId: B
                relativeTimeRange:
                  from: 300
                  to: 0
                datasourceUid: __expr__
                model:
                  conditions:
                    - evaluator:
                        params:
                          - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                          - B
                      reducer:
                        params: []
                        type: last
                      type: query
                  datasource:
                    type: __expr__
                    uid: __expr__
                  expression: A
                  intervalMs: 1000
                  maxDataPoints: 43200
                  reducer: last
                  refId: B
                  type: reduce
              - refId: C
                relativeTimeRange:
                  from: 300
                  to: 0
                datasourceUid: __expr__
                model:
                  conditions:
                    - evaluator:
                        params:
                          - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                          - C
                      reducer:
                        params: []
                        type: last
                      type: query
                  datasource:
                    type: __expr__
                    uid: __expr__
                  expression: B
                  intervalMs: 1000
                  maxDataPoints: 43200
                  type: math
                  refId: C
            noDataState: OK
            execErrState: Error
            for: 1m
            annotations:
              description: "Pod {{ "{{" }} $labels.namespace {{ "}}" }}/{{ "{{" }} $labels.pod {{ "}}" }} is restarting."
              summary: "Pod Crash Loop"
            labels:
              severity: critical
