{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secrets
  namespace: data
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/managed-by: Helm
type: Opaque
stringData:
  MONGODB_BACKUP_USER: backup
  MONGODB_BACKUP_PASSWORD: {{ .Values.mongodb.backupPassword | default "backupSecret123" | quote }}
  MONGODB_DATABASE_ADMIN_USER: databaseAdmin
  MONGODB_DATABASE_ADMIN_PASSWORD: {{ .Values.mongodb.adminPassword | default "dbAdminSecret123" | quote }}
  MONGODB_CLUSTER_ADMIN_USER: clusterAdmin
  MONGODB_CLUSTER_ADMIN_PASSWORD: {{ .Values.mongodb.clusterAdminPassword | default "clusterAdminSecret123" | quote }}
  MONGODB_CLUSTER_MONITOR_USER: clusterMonitor
  MONGODB_CLUSTER_MONITOR_PASSWORD: {{ .Values.mongodb.monitorPassword | default "clusterMonitorSecret123" | quote }}
  MONGODB_USER_ADMIN_USER: userAdmin
  MONGODB_USER_ADMIN_PASSWORD: {{ .Values.mongodb.userAdminPassword | default "userAdminSecret123" | quote }}
{{- end }}
