{{- if .Values.mongodb.enabled }}
apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  name: mongodb
  namespace: data
  labels:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/managed-by: Helm
spec:
  crVersion: 1.23.0
  image: {{ .Values.mongodb.image | default "percona/percona-server-mongodb:8.0.26-11" }}
  imagePullPolicy: IfNotPresent
  unsafeFlags:
    tls: true
  secrets:
    users: mongodb-secrets
  upgradeOptions:
    apply: disabled
  replsets:
    - name: rs0
      size: {{ .Values.mongodb.clusterSize | default 1 }}
      volumeSpec:
        emptyDir: {}
      resources:
        {{- toYaml .Values.mongodb.resources | nindent 8 }}
      affinity:
        advanced:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: kubernetes.io/hostname
                      operator: In
                      values:
                        - {{ .Values.mongodb.nodeHostname | default .Values.mongodb.nodeSelector | default "arm10" }}
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/name
                        operator: In
                        values:
                          - mongodb
                  topologyKey: kubernetes.io/hostname
{{- end }}
