{{- if .Values.pulsar.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fleet-pulsar-zookeeper-data-0
  labels:
    type: local
    app: pulsar-zookeeper
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /home/thang/pulsar/zookeeper/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - arm10
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fleet-pulsar-bookie-journal-0
  labels:
    type: local
    app: pulsar-bookkeeper
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /home/thang/pulsar/bookkeeper/journal
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - arm10
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fleet-pulsar-bookie-ledgers-0
  labels:
    type: local
    app: pulsar-bookkeeper
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /home/thang/pulsar/bookkeeper/ledgers
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - arm10
{{- end }}
