{{- if .Values.redisReplication.enabled }}
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: RedisReplication
metadata:
  name: redis
  namespace: data
  labels:
    app.kubernetes.io/name: redis
spec:
  clusterSize: {{ .Values.redisReplication.clusterSize | default 1 }}
  kubernetesConfig:
    image: {{ .Values.redisReplication.image | default "quay.io/opstree/redis:v7.4.11" }}
    imagePullPolicy: IfNotPresent
    resources:
      {{- toYaml .Values.redisReplication.resources | nindent 10 }}
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - {{ .Values.redisReplication.nodeHostname | default .Values.redisReplication.nodeSelector | default "arm10" }}
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - redis
            topologyKey: kubernetes.io/hostname
{{- end }}
