apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  namespace: apps
  labels:
    app: vaultwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultwarden
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      nodeSelector:
        kubernetes.io/hostname: arm10
      containers:
        - name: vaultwarden
          image: {{ .Values.vaultwarden.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
            - containerPort: 3012
              name: websocket
          env:
            - name: WEBSOCKET_ENABLED
              value: "true"
            - name: SIGNUPS_ALLOWED
              value: "true"
            - name: INVITATIONS_ALLOWED
              value: "true"
            - name: DOMAIN
              value: "https://vault.vinhthang.dev"
            - name: ROCKET_PORT
              value: "80"
          livenessProbe:
            httpGet:
              path: /alive
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /alive
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
          volumeMounts:
            - name: vaultwarden-data
              mountPath: /data
          resources:
            {{- toYaml .Values.vaultwarden.resources | nindent 12 }}
      volumes:
        - name: vaultwarden-data
          hostPath:
            path: /opt/vaultwarden
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: vaultwarden
  namespace: apps
spec:
  type: NodePort
  selector:
    app: vaultwarden
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: {{ .Values.vaultwarden.nodePort }}
    - name: websocket
      protocol: TCP
      port: 3012
      targetPort: 3012
